config/routes.rb
Rails.application.routes.draw do

  root 'lands#index'

  get 'interns/index'
  get 'ambassadors/index'

  resources :interns do
  end
  resources :ambassadors do
  end
  resources :lands do
  end
  resources :inventors do
  end
  resources :products do
  end

end

app/models/ambassador.rb
class Ambassador < ActiveRecord::Base
end

app/models/intern.rb
class Intern < ActiveRecord::Base
end

app/models/inventor.rb
class Inventor < ActiveRecord::Base
end

app/models/land.rb
class Land < ActiveRecord::Base
end

app/controllers/ambassadors_controller.rb
class AmbassadorsController < ApplicationController
	def index
	end

	def new
  	end

  	def create
    	@ambassador = Ambassador.new(ambassador_params)
    	if @ambassador.save
        AmbMailer.contact_created(@ambassador.name,@ambassador.email,@ambassador.college,@ambassador.course,@ambassador.year,@ambassador.number).deliver
        AmbtusharMailer.contact_created(@ambassador.name,@ambassador.email,@ambassador.college,@ambassador.course,@ambassador.year,@ambassador.number).deliver
     		 redirect_to root_path, notice: "successfully sent"
    	else
     		 render ambassadors_path
   		 end
  	end

  	private

    def ambassador_params
    params.require(:ambassador).permit(:name, :college, :course, :year, :email, :number)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/interns_controller.rb
class InternsController < ApplicationController
	def index
	end

	def new
  	end

  	def create
    	@intern = Intern.new(intern_params)
    	if @intern.save
        InternMailer.contact_created(@intern.name,@intern.email,@intern.college,@intern.course,@intern.year,@intern.number,@intern.field).deliver
        InterntusharMailer.contact_created(@intern.name,@intern.email,@intern.college,@intern.course,@intern.year,@intern.number,@intern.field).deliver
     		 redirect_to root_path, notice: "successfully sent"
    	else
     		 render interns_path
   		 end
  	end

  	private

    def intern_params
    params.require(:intern).permit(:name, :college, :course, :year, :email, :number, :field)
    end

end

app/controllers/inventors_controller.rb
class InventorsController < ApplicationController
	def index
	end

	def new
  	end

  	 	def create
    	@inventor = Inventor.new(inventor_params)
    	if @inventor.save
    	InventorMailer.contact_created(@inventor.email).deliver
    	InvtusharMailer.contact_created(@inventor.name,@inventor.organisation,@inventor.email,@inventor.number,@inventor.intro).deliver
     		 redirect_to root_path, notice: "successfully sent"
    	else
     		 render inventors_path
   		 end
  	end

  	private

    def inventor_params
    params.require(:inventor).permit(:name, :organisation, :email, :number, :intro)
    end
end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
	def index
	end

	def new
  	end

    def product
    end

    def inventors
    end

  	def create
    	@land = Land.new(land_params)
    	if @land.save
        ContactusMailer.contact_created(@land.email).deliver
        CttMailer.contact_created(@land.firstname,@land.lastname,@land.email,@land.subject,@land.message).deliver
     		 redirect_to root_path, notice: "Message was successfully sent"
    	else
     		 render root_path
   		 end
  	end

  	private

    def land_params
    params.require(:land).permit(:firstname, :lastname, :email, :subject, :message)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
	end

	def new
  	end
end

app/helpers/ambassador_helper.rb
module AmbassadorHelper
end

app/helpers/ambassadors_helper.rb
module AmbassadorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/intern_helper.rb
module InternHelper
end

app/helpers/interns_helper.rb
module InternsHelper
end

app/helpers/inventors_helper.rb
module InventorsHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/ambassadors/index.html.erb
  <header id="main-header">

   	<div class="row header-inner">

	      <div class="logo">
	         <a class="smoothscroll" href="#hero">EZe Innovations.</a>
	      </div>

	      <nav id="nav-wrap">         
	         
	         <a class="mobile-btn" href="#nav-wrap" title="Show navigation">
	         	<span class='menu-text'>Show Menu</span>
	         	<span class="menu-icon"></span>
	         </a>
         	<a class="mobile-btn" href="#" title="Hide navigation">
         		<span class='menu-text'>Hide Menu</span>
         		<span class="menu-icon"></span>
         	</a>         

	         <ul id="nav" class="nav">	            
	            <li><a class="smoothscroll" href="#contact">Ambassador Programm.</a></li>
	         </ul> 

	      </nav> <!-- /nav-wrap -->	      

	   </div> <!-- /header-inner -->

   </header>
<section id="contact"> 
    <div class="row section-head">

   		<div class="twelve columns">

	         <h1>Represnt EZe in your college<span>.</span></h1>

	         <hr />

	         <p>Be our college Ambassadaor</p>

	      </div>

      </div>
<div class="row form-section">
      	
      	<div id="contact-form" class="twelve columns">

            <form name="contactForm" id="contactForm" method="post" action="">

      			<fieldset>

                  <div class="row">
                    
                <div class="six columns mob-whole">   
<%= form_for(:ambassador, :url => {:action => "create"}, :html => {:multipart => true}) do |f| %>
            <%= f.text_field :name, class:"six columns mob-whole", placeholder: "Name" %> <br />
            <%= f.text_field :college, class:"six columns mob-whole", placeholder: "College" %> <br />
            <%= f.text_field :course, class:"six columns mob-whole", placeholder: "Course" %> <br />
            <%= f.email_field :email, class:"six columns mob-whole", placeholder: "Email" %><br />
            <%= f.text_field :year, class:"six columns mob-whole", placeholder: "Year" %> <br />
            <%= f.text_field :number, class:"six columns mob-whole", placeholder: "Number" %> <br />
	    <input type="submit" value="Send">
	 <% end %>
      <!-- /form-section -->   
                      </div>
                    </div>
                </fieldset>
            </form>
    </div>
    </div>
    
</section>

  <footer> 
         
      <div class="row">   
           
        <div class="six columns tab-whole right-cols">

            <div class="row">
                
               <div class="columns last">
                   
                   <h3 class="contact">Follow Us</h3>
                  <ul>
                     <li><a href="https://www.facebook.com/ezeinnovations95/?fref=ts">Facebook</a></li>
                     <li><a href="https://www.linkedin.com/company/7165863?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A7165863%2Cidx%3A1-1-1%2CtarId%3A1451728030217%2Ctas%3Aeze%20inn ">LinkedIn</a></li>
                   </ul>
               </div> <!-- /columns --> 
            </div> <!-- /Row(nested) -->
          </div>
         
         <p class="copyright">&copy; Copyright 2016 EZe Innovations. Developed by <a href="https://www.facebook.com/shivin.agarwal.12">Shivin Agarwal.</a></p>
          
         <div id="go-top">
            <a class="smoothscroll" title="Back to Top" href="#hero"><span>Top</span><i class="fa fa-long-arrow-up"></i></a>
         </div>
      </div> <!-- /row -->
   </footer> <!-- /footer -->

   
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script>window.jQuery || document.write('<script src="assets/jquery-1.10.2.min.js"><\/script>')</script>
    <script type="text/javascript" src="assets/jquery-migrate-1.2.1.min.js"></script>   
 <!--  <script src="assets/jquery.flexslider.js"></script> -->
   <script src="assets/jquery.fittext.js"></script>
   <script src="assets/backstretch.js"></script> 
   <script src="assets/waypoints.js"></script>  
   <script src="assets/main.js"></script>
                    

app/views/interns/index.html.erb
  <header id="main-header">

   	<div class="row header-inner">

	      <div class="logo">
	         <a class="smoothscroll" href="#hero">EZe Innovations.</a>
	      </div>

	      <nav id="nav-wrap">         
	         
	         <a class="mobile-btn" href="#nav-wrap" title="Show navigation">
	         	<span class='menu-text'>Show Menu</span>
	         	<span class="menu-icon"></span>
	         </a>
         	<a class="mobile-btn" href="#" title="Hide navigation">
         		<span class='menu-text'>Hide Menu</span>
         		<span class="menu-icon"></span>
         	</a>         

	         <ul id="nav" class="nav">	            
	            <li><a class="smoothscroll" href="#contact">Internship.</a></li>
	         </ul> 

	      </nav> <!-- /nav-wrap -->	      

	   </div> <!-- /header-inner -->

   </header>
<section id="contact">
    <div class="row section-head">

   		<div class="twelve columns">

	         <h1>EZe Brings you with internship programs<span>.</span></h1>

	         <hr />

	         <p>Give us your details us!</p>

	      </div>

      </div>
    <div class="row form-section">
      	
      	<div id="contact-form" class="twelve columns">

            <form name="contactForm" id="contactForm" method="post" action="">

      			<fieldset>

                  <div class="row">
                    
                <div class="six columns mob-whole">

<%= form_for(:intern, :url => {:action => "create"}, :html => {:multipart => true}) do |f| %>
            <%= f.text_field :name, class:"six columns mob-whole", placeholder: "Name" %> <br />
            <%= f.text_field :college, class:"six columns mob-whole", placeholder: "College" %> <br />
            <%= f.text_field :course, class:"six columns mob-whole", placeholder: "Course" %> <br />
            <%= f.email_field :email, class:"six columns mob-whole", placeholder: "Email" %><br />
            <%= f.text_field :year, class:"six columns mob-whole", placeholder: "Year" %> <br />
            <%= f.text_field :number, class:"six columns mob-whole", placeholder: "Number" %> <br />
            <%= f.text_field :field, class:"six columns mob-whole", placeholder: "Field Of Interest" %> <br />
	    <input type="submit" value="Send">
	 <% end %>
      <!-- /form-section -->   
                      </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</section>

  <footer> 
         
      <div class="row">   
           
        <div class="six columns tab-whole right-cols">

            <div class="row">
                
               <div class="columns last">
                   
                   <h3 class="contact">Follow Us</h3>
                  <ul>
                     <li><a href="https://www.facebook.com/ezeinnovations95/?fref=ts">Facebook</a></li>
                     <li><a href="https://www.linkedin.com/company/7165863?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A7165863%2Cidx%3A1-1-1%2CtarId%3A1451728030217%2Ctas%3Aeze%20inn ">LinkedIn</a></li>
                   </ul>
               </div> <!-- /columns --> 
            </div> <!-- /Row(nested) -->
          </div>
         
         <p class="copyright">&copy; Copyright 2016 EZe Innovations. Developed by <a href="https://www.facebook.com/shivin.agarwal.12">Shivin Agarwal.</a></p>
          
         <div id="go-top">
            <a class="smoothscroll" title="Back to Top" href="#hero"><span>Top</span><i class="fa fa-long-arrow-up"></i></a>
         </div>
      </div> <!-- /row -->
   </footer> <!-- /footer -->
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script>window.jQuery || document.write('<script src="assets/jquery-1.10.2.min.js"><\/script>')</script>
    <script type="text/javascript" src="assets/jquery-migrate-1.2.1.min.js"></script>   
 <!--  <script src="assets/jquery.flexslider.js"></script> -->
   <script src="assets/jquery.fittext.js"></script>
   <script src="assets/backstretch.js"></script> 
   <script src="assets/waypoints.js"></script>  
   <script src="assets/main.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <title>EZe innovations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
   <!--- Basic Page Needs
   ================================================== -->
   <meta charset="utf-8">
	<title>EZe Innovations</title>
	<meta name="description" content="">  
	<meta name="author" content="">
   <!-- Mobile Specific Metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- CSS
    ================================================== -->  
   <!-- Script
   =================================================== -->
   <script src="assets/modernizr.js"></script>   
</head>

<body class="homepage">
   <!-- Header
   =================================================== -->
   <header id="main-header">
   	<div class="row header-inner">
	      <div class="logo">
	         <a class="smoothscroll" href="#hero">EZe Innovations.</a>
	      </div>
	      <nav id="nav-wrap">         
	         <a class="mobile-btn" href="#nav-wrap" title="Show navigation">
	         	<span class='menu-text'>Show Menu</span>
	         	<span class="menu-icon"></span>
	         </a>
         	<a class="mobile-btn" href="#" title="Hide navigation">
         		<span class='menu-text'>Hide Menu</span>
         		<span class="menu-icon"></span>
         	</a>         
	         <ul id="nav" class="nav">
                 <li class="current"><a class="smoothscroll" href="#about">Product Design Consultancy.</a></li>
	         </ul> 
	      </nav> <!-- /nav-wrap -->	      
	   </div> <!-- /header-inner -->
   </header> 
 <section id="page-title">	
   	  
		<div class="row">

			<div class="twelve columns">

				<h1>Product Design Consultancy<span>.</span></h1

			</div>			    

		</div> <!-- /row -->	   

   </section> <!-- /page-title -->

   <!-- Hero
   =================================================== -->
   <!-- About Section
   ================================================== -->
   <section id="about">
<br>
   	<div class="row section-head">

   		<div class="twelve columns">

	         <h1>About<span>.</span></h1>

	         <hr />
	<div class="row section-head">

   		<div class="twelve columns">

	         <p>We are open to collaborate with other companies to Design And Develop their product and Optimize the product they are already having. We Innovate at every step to make a product more usable and cheaper for the masses. We seek that Perfection Out.

</p>
             </div>

      </div>
            <h1>Our Specialisation<span>.</span></h1>
            <hr />
<p>
Concept design, Aesthetics & Ergonomics, Design for Functionality, Value Engineering, Reverse Engineering, CAD Drafting, Embedded Electronics, Modelling of Plastic Parts & Assemblies, GD&T, Production Drawings, Tolerance stack-up analysis, snap fit validation studies & Research</p>

	      </div>

      </div>

      <div class="row about-content"> 

      	<div class="mob-whole six columns left">

      		<h3>Product Designing & Development.</h3>	

	      	<p>We put every nut and bolt at their perfect place for the perfect product.
	         </p>

      	</div> <!-- /left -->

      	<div class="mob-whole six columns right">

	      	<h3>Product Innovation .</h3>

	      	<p>Innovation is the pillar of growth, So we Innovate the product and provide consultancy services for the new product
	         </p>	

      	</div> <!-- /right -->

      </div> <!-- /row -->    

      <div class="row about-content"> 

      	<div class="mob-whole six columns left">

	      	<h3>Prototyping.</h3>	

	      	<p>Every Product needs to be felt physically. We Prototype your product.</p>

      	</div> <!-- /left -->

      	<div class="mob-whole six columns right">

	      	<h3>CAD Drafting.</h3>
	      	<p>We not only design, We provide you Manufacturing Ready Designs.
	         </p>	

      	</div> <!-- /right -->

      </div> <!-- /row -->
            <div class="row about-content"> 

      	<div class="mob-whole six columns left">

	      	<h3>Concept Development.</h3>	

	      	<p>You Think, We help you develop that Concept.</p>

      	</div> <!-- /left -->
                
      </div> <!-- /row -->
           <!-- <h3><%= link_to "Go Back", lands_path, class: "button primary full-width"  %></h3> -->
            <br>
            <br>
            <br>
            <br>

    </section>
            
            <footer>
                 <div class="row">   
         <div id="go-top">
            <a class="smoothscroll" title="Back to Top" href="#about"><span>Top</span><i class="fa fa-long-arrow-up"></i></a>
                     </div>
                </div>
   </footer> <!-- /footer -->
   
   
   <!-- Java Script
   ================================================== -->
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script>window.jQuery || document.write('<script src="/assets/jquery-1.10.2.min.js"><\/script>')</script>
    <script type="text/javascript" src="/assets/jquery-migrate-1.2.1.min.js"></script>   
   <script src="assets/jquery.fittext.js"></script>
   <script src="assets/backstretch.js"></script> 
   <script src="assets/waypoints.js"></script>  
   <script src="assets/main.js"></script>

</body>

</html>